### ISSUE TITLE
发Resource的时候自动检测网页标题怎么样？

### ISSUE THREAD

**Issue by cqpx** [chloerei/code_campo#1]
就不需要再自己手动输入了

**Comment by chloerei** [comment]
这个有考虑过做，但是实际做了之后有一些麻烦：
1. 标题通常不会很理想，比如 '- topic - codecampo‘ 这些字符应该排除
2. 如果抓得不理想，就要提供编辑，但是不希望提供编辑（管理员编辑）
3. 始终需要编辑 tag

甚至还写过一个 bookmarklet，用弹窗方式被浏览器阻止，用 frame 的话代码量比较多还没尝试。

综合来说，要做一个功能的话就要各方面都完善，不然就还是用质朴的方法。如果有心投递的话，会接受认真编辑一个标题，而不是网址随手贴。
