### ISSUE TITLE
本地部署的时候报错

### ISSUE THREAD

**Issue by zuoyang** [chloerei/code_campo#13]
做 rake db:seed 这步的时候报错：

“Gem::LoadError: You have already activated rake 10.3.2, but your Gemfile requires rake 10.1.0. Prepending `bundle exec` to your command may solve this. ”

在stackflow上找到答案，说要在Gemfile里面指定 rake 版本，
gem 'rake', '10.1.0'

添加后，还是报错，然后又按照方法，用

bundle exec rake db:seed

执行，然后就是一大串报错：

/Users/young/.rvm/gems/ruby-2.1.0/gems/redcarpet-2.1.1/lib/redcarpet.bundle: [BUG] Segmentation fault at 0x00000000000418
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin12.0]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     \* ~/Library/Logs/CrashReporter
     \* /Library/Logs/CrashReporter
     \* ~/Library/Logs/DiagnosticReports
     \* /Library/Logs/DiagnosticReports
   for more details.

-- Control frame information -----------------------------------------------
c:0026 p:-545542170 s:0087 e:000086 TOP    [FINISH]
c:0025 p:---- s:0085 e:000084 CFUNC  :require
c:0024 p:0007 s:0081 e:000080 TOP    /Users/young/.rvm/gems/ruby-2.1.0/gems/redcarpet-2.1.1/lib/redcarpet.rb:1 [FINISH]
c:0023 p:---- s:0079 e:000078 CFUNC  :require
c:0022 p:0037 s:0075 e:000074 BLOCK  /Users/young/.rvm/gems/ruby-2.1.0/gems/bundler-1.6.0.rc2/lib/bundler/runtime.rb:76 [FINISH]
c:0021 p:---- s:0072 e:000071 CFUNC  :each
c:0020 p:0055 s:0069 e:000068 BLOCK  /Users/young/.rvm/gems/ruby-2.1.0/gems/bundler-1.6.0.rc2/lib/bundler/runtime.rb:72 [FINISH]
c:0019 p:---- s:0062 e:000061 CFUNC  :each
c:0018 p:0030 s:0059 e:000058 METHOD /Users/young/.rvm/gems/ruby-2.1.0/gems/bundler-1.6.0.rc2/lib/bundler/runtime.rb:61
c:0017 p:0013 s:0055 e:000054 METHOD /Users/young/.rvm/gems/ruby-2.1.0/gems/bundler-1.6.0.rc2/lib/bundler.rb:132
c:0016 p:0093 s:0051 e:000050 TOP    /Users/young/code_campo/config/application.rb:13 [FINISH]
c:0015 p:---- s:0049 e:000048 CFUNC  :require
c:0014 p:0018 s:0045 e:000044 TOP    /Users/young/code_campo/Rakefile:5 [FINISH]
c:0013 p:---- s:0043 e:000042 CFUNC  :load
c:0012 p:0009 s:0039 e:000038 METHOD /Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/rake_module.rb:25
c:0011 p:0176 s:0035 e:000034 METHOD /Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:637
c:0010 p:0007 s:0030 e:000029 BLOCK  /Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:94
c:0009 p:0006 s:0028 e:000027 METHOD /Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:165
c:0008 p:0007 s:0024 e:000023 METHOD /Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:93
c:0007 p:0013 s:0021 e:000020 BLOCK  /Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:77
c:0006 p:0006 s:0019 e:000018 METHOD /Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:165
c:0005 p:0007 s:0015 e:000014 METHOD /Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:75
c:0004 p:0040 s:0012 e:000011 TOP    /Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.0/bin/rake:33 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0135 s:0006 E:0025b8 EVAL   /Users/young/.rvm/gems/ruby-2.1.0/bin/rake:23 [FINISH]
c:0001 p:0000 s:0002 E:002518 TOP    [FINISH]

/Users/young/.rvm/gems/ruby-2.1.0/bin/rake:23:in `<main>'
/Users/young/.rvm/gems/ruby-2.1.0/bin/rake:23:in`load'
/Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:75:in`run'
/Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:165:in `standard_exception_handling'
/Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:77:in`block in run'
/Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:93:in `load_rakefile'
/Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:165:in`standard_exception_handling'
/Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:94:in `block in load_rakefile'
/Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/application.rb:637:in`raw_load_rakefile'
/Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/rake_module.rb:25:in `load_rakefile'
/Users/young/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/rake/rake_module.rb:25:in`load'
/Users/young/code_campo/Rakefile:5:in `<top (required)>'
/Users/young/code_campo/Rakefile:5:in`require'
/Users/young/code_campo/config/application.rb:13:in `<top (required)>'
/Users/young/.rvm/gems/ruby-2.1.0/gems/bundler-1.6.0.rc2/lib/bundler.rb:132:in`require'
/Users/young/.rvm/gems/ruby-2.1.0/gems/bundler-1.6.0.rc2/lib/bundler/runtime.rb:61:in `require'
/Users/young/.rvm/gems/ruby-2.1.0/gems/bundler-1.6.0.rc2/lib/bundler/runtime.rb:61:in`each'
...此处省略，太长了
rb
  916 /Users/young/.rvm/gems/ruby-2.1.0/gems/gravtastic-3.2.6/lib/gravtastic/engine.rb
  917 /Users/young/.rvm/gems/ruby-2.1.0/gems/gravtastic-3.2.6/lib/gravtastic.rb
  918 /Users/young/.rvm/gems/ruby-2.1.0/gems/wmd-rails-0.0.7/lib/wmd/rails/engine.rb
  919 /Users/young/.rvm/gems/ruby-2.1.0/gems/wmd-rails-0.0.7/lib/wmd/version.rb
  920 /Users/young/.rvm/gems/ruby-2.1.0/gems/wmd-rails-0.0.7/lib/wmd-rails.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6

这是咋回事，求解？

**Comment by chloerei** [comment]
用 `bundle exec rake db:seed`

**Comment by zuoyang** [comment]
我最后一次用的就是 bundle exec rake db:seed ，还是上那样报错

**Comment by zuoyang** [comment]
/Users/young/.rvm/gems/ruby-2.1.0/gems/redcarpet-2.1.1/lib/redcarpet.bundle: [BUG] Segmentation fault at 0x00000000000418
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin12.0]

-- Crash Report log information --------------------------------------------
See Crash Report log file under the one of following:
- ~/Library/Logs/CrashReporter
- /Library/Logs/CrashReporter
- ~/Library/Logs/DiagnosticReports
- /Library/Logs/DiagnosticReports
  for more details.
  rb
  916 /Users/young/.rvm/gems/ruby-2.1.0/gems/gravtastic-3.2.6/lib/gravtastic/engine.rb
  917 /Users/young/.rvm/gems/ruby-2.1.0/gems/gravtastic-3.2.6/lib/gravtastic.rb
  918 /Users/young/.rvm/gems/ruby-2.1.0/gems/wmd-rails-0.0.7/lib/wmd/rails/engine.rb
  919 /Users/young/.rvm/gems/ruby-2.1.0/gems/wmd-rails-0.0.7/lib/wmd/version.rb
  920 /Users/young/.rvm/gems/ruby-2.1.0/gems/wmd-rails-0.0.7/lib/wmd-rails.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6

**Comment by zuoyang** [comment]
把rake所有版本都删了，然后只装10.1.0 ,就解决了

**Comment by windy** [comment]
@zuoyang 实际上使用 bundle exec rake db:seed 就好了.
