### ISSUE TITLE
lack of installation instruction or app_config.sample.yml file

### ISSUE THREAD

**Issue by yuest** [chloerei/code_campo#2]
How can I install it to my own server.

**Comment by chloerei** [comment]
```
cp config/app_config.example.yml config/app_config.yml
cp config/mongoid.example.yml config/mongoid.yml
rails s
```

require mongodb running.

**Comment by yuest** [comment]
do we have a default admin account or something? how can i bootstrap it?

**Comment by yuest** [comment]
admin dashboard?

**Comment by chloerei** [comment]
There are no admin yet, and no admin panel. I manager website by rails console on server.

Admin panel is on plant, but not imperative for codecampo.com, and code_campo is no a common project any more.

**Comment by zernel** [comment]
```
cp config/app_config.example.yml config/app_config.yml
cp config/mongoid.example.yml config/mongoid.yml
rails s
```

Why don't add these to README?

**Comment by chloerei** [comment]
Added README.
