### ISSUE TITLE
在bundle install的时候出现问题

### ISSUE THREAD

**Issue by jodis** [chloerei/code_campo#3]
ror新手~使用zip包下载源代码后cd到目录执行bundle install出现如下问题~
是git配置不对的原因吗？求解~谢谢~

E:\dev\ruby\code_campo>bundle install
Fetching git://github.com/bcardarella/client_side_validations.git
Unfortunately, a fatal error has occurred. Please report this error to the Bundl
er issue tracker at https://github.com/carlhuda/bundler/issues so that we can fi
x it. Please include the full output of the command, your Gemfile and Gemfile.lo
ck. Thanks!
d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/source.rb:592:in `
`': No such file or directory - git clone "git://github.com/bcardarella/client_s
ide_validations.git" "d:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/client_si
de_validations-1f04c5ec97583337510881f8ffe18e720a45ff58" --bare --no-hardlinks (
Errno::ENOENT)
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/sourc
e.rb:592:in `git'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/sourc
e.rb:654:in`cache'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/sourc
e.rb:553:in `specs'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/defin
ition.rb:188:in`block in resolve'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/defin
ition.rb:186:in `each'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/defin
ition.rb:186:in`resolve'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/defin
ition.rb:127:in `specs'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/defin
ition.rb:122:in`resolve_remotely!'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/insta
ller.rb:48:in `run'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/insta
ller.rb:12:in`install'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/cli.r
b:220:in `install'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendo
r/thor/task.rb:22:in`run'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendo
r/thor/invocation.rb:118:in `invoke_task'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendo
r/thor.rb:263:in`dispatch'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendo
r/thor/base.rb:386:in `start'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/bin/bundle:13:in
`<top (required)>'
        from d:/Ruby193/bin/bundle:19:in `load'
        from d:/Ruby193/bin/bundle:19:in`<main>'

**Comment by chloerei** [comment]
我不了解 windows 的环境。git 安装正常吗？可以 clone 项目了吗？

github 的安装教程（第一部分） http://help.github.com/win-set-up-git/

**Comment by jodis** [comment]
windows版的git安裝正常～也可以clone到項目～
d:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/source.rb:592:in 
': No such file or directory - git clone "git://github.com/bcardarella/client_s
ide_validations.git" "d:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/client_si
de_validations-1f04c5ec97583337510881f8ffe18e720a45ff58" --bare --no-hardlinks (
Errno::ENOENT)
看到這段的時候～執行了gem install git～然後gem也裝了一個版本的git
但是執行bundle install還是報同樣的錯誤…

**Comment by keyvec** [comment]
使用最新版本的ruby，注意翻墙，如果使用到要本地编译的gem，需要安装编译相关的工具。解决不了就换Linux环境。

**Comment by chloerei** [comment]
https://groups.google.com/forum/?fromgroups#!topic/rubyinstaller/ASl2sOqMs6U

这里有个相似的问题，看来还是 git 的安装问题

确保用 github 的教程安装 git ，http://help.github.com/win-set-up-git/ ，并且 bundle 的时候在 git bash 里面操作。

**Comment by jodis** [comment]
把path加进去环境变量就好了……囧~
谢谢~
